services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - ./env/postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    env_file:
      - ./env/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
